config/routes.rb
Phaseboot::Application.routes.draw do

  mount Forem::Engine, :at => '/forums'

  root to: "pages#index"
  get "/admin" => "pages#admin", :as => :admin
  post '/pages/search'
  get '/auth/:provider/callback', to: 'sessions#create'
  post '/search' => 'users#query'
  get '/users/cohort_reselect'

  match "/signout" => "sessions#destroy", :as => :signout

  resources :users do
    get "/photo" => "users#photo"
  end

  resources :sessions, only: [:new, :create, :destroy]
  resources :access, only: [:show]
  
  resources :cohorts do
    resources :users, only: [:index]
  end

  

end

app/models/user.rb
class User < ActiveRecord::Base
  attr_accessible :first_name, :last_name, :email, :nickname, :phone_number,
                  :company, :location, :advice, :restaurant, :website_url, :blog_url, 
                  :cohort_id, :photo_url, :github_uid, :provider, :github_token,
                  :facebook_url, :twitter_url, :linkedin_url
                  
  # validates :cohort_id, presence: true
  validates :github_uid, presence: true, uniqueness: true
  validates :github_token, presence: true
  # validates :email, format: {with: /[\w\-\.]+@[\w\-\.]+\.[\w]{2,7}/i}

  before_save :format_fields

  belongs_to :cohort
  has_one :admin

  def upload_avatar(photo_url)
    s3 = AWS::S3.new
    bucket = s3.buckets['bootconnect']
    file = open(photo_url)
    basename = "#{self.first_name}-#{SecureRandom.hex(14)}.png"
    o = bucket.objects[basename]
    o.write(:file => file)
    o.public_url.to_s
  end

  def format_fields
    self.facebook_url = self.facebook_url.gsub(/.*\//, '') if self.facebook_url
    self.twitter_url = self.twitter_url.gsub(/.*\//, '') if self.twitter_url
  end

  def phone_number=(num)
    if num.present? 
      self.phone = num.split('').select{|l| l =~ /\d/ }.join
    else
      self.phone = "000000000"
    end
  end

  def phone_number
    "#{self.phone[0..2]}-#{self.phone[3..5]}-#{self.phone[6..9]}"
  end

  def adminify!
    Admin.find_or_create_by_user_id(self.id)
  end

  def admin?
    Admin.exists?(user_id: self.id)
  end

  def name
    "#{self.first_name} #{self.last_name}"
  end

  def photo
    return photo_url if self.photo_url =~ /\w/
    return "/assets/default-profile-image.gif"
  end

  class << self
    def current
      Cohort.includes(:users).current.map { |cohort| cohort.users }.flatten
    end

    def pictured
      current.select{|user| user.photo_url }
    end

    def wise
      pictured.select{|user| user.advice && user.advice.length > 0 }
    end

    def featured
      wise.sample
    end
  end

  def to_s
    self.first_name
  end


end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  before_filter :auth_admin, only: [:destroy]
  skip_before_filter :auth, only: [:edit_cohort]

  def index
    if params[:cohort_id]
      @cohort = Cohort.find(params[:cohort_id])
      @users = @cohort.users
    else
      @users = User.all(:conditions => "photo_url != ''")
    end
  end

  def create
  end

  def new
  end

  def edit
    @user = User.find(current_user)
    @avatars = avatars_by_cohort(@user.cohort)
    @show_facebook = Provider.where("user_id = ? AND name = ?", @user.id, :facebook).count > 0 ? false : true
    @show_twitter = Provider.where("user_id = ? AND name = ?", @user.id, :twitter).count > 0 ? false : true
  end

  def show
    @user = User.find(params[:id])
  end 

  def update
    @user = User.find(current_user.id)
    params[:user][:photo_url] = @user.upload_avatar(params[:user][:photo_url]) if params[:user][:photo_url]
    @user.update_attributes(params[:user])
    if @user.photo_url
      redirect_to user_path(@user)
    else
      redirect_to edit_user_path(@user), :notice => "You must select your photo!"
    end
  end

  def destroy
    user = User.find(params[:id])
    if user.destroy
      redirect_to users_path, :notice => "Successfully destroyed"
    else
      redirect_to users_path, :error => "There was an issue"
    end
  end

  def logout
    reset_session
  end

  def query
    search = User.search do
      fulltext params[:phrase]
    end
    p search.results
    render json: search.results
  end

  def cohort_reselect
    @user = current_user
    @cohorts = Cohort.all
  end

  def photo
    @user = User.find(params[:user_id])
    @avatars = avatars_by_cohort(@user.cohort)
  end

private

  def avatars_by_cohort(cohort)
    doc = Nokogiri::HTML(open(cohort.photos_url))
    doc.css("ol#gallery-view-media li img").map { |li| {src: li['data-src'], id: cohort.id} }
  end

  def avatars
    imgs = []
    
    Cohort.all.each do |cohort|
      if cohort.photos_url
        doc = Nokogiri::HTML(open(cohort.photos_url))
        imgs << doc.css("ol#gallery-view-media li img").map { |li| {src: li['data-src'], id: cohort.id} }
      end
    end

    imgs.flatten
  end
end

app/helpers/user_helper.rb
module UserHelper
  def avatar(name, avatars)
    return avatars.select {|img| img.include? name }.first if name && avatars.length
    return "https://dt8kf6553cww8.cloudfront.net/static/images/preview_fail-vfloJ3Dyo.png"
  end
end

app/views/users/_photos.html.erb
<ul class="avatars">
  <% @avatars.each do |img| %>
    <% select = img[:src].include?(@user.first_name.downcase) %>
    <li class="avatar <%= select ? 'selected' : '' %> <%= "cohort_#{img[:id]}" %>">
      <%= f.radio_button :photo, img[:src], :checked => select  %>
      <%= image_tag img[:src] %>
    </li>
  <% end %>
</ul>

app/views/users/_quickinfo.html.erb
<div class="quickinfo">
	
		<%= image_tag('x-mark-4-32.png', :class => 'close') %>
	
	<ul>
		
		<li><%= mail_to "#{user.email}" %></li>
	  <li><%= phone_number_link(user.phone_number) %></li>
	  <li><%= link_to user.website_url, "http://#{user.website_url}" %></li>
	  <li><%= link_to user.blog_url, "http://#{user.blog_url}" %></li>
	  
	  <li>
		  <%= link_to image_tag('github_icon.png', :class => 'social_icons'), "http://github.com/#{user.nickname}" %>
		  <% unless user.facebook_url.blank? %>
		  	<%= link_to image_tag('facebook_icon.png', :class => 'social_icons'), "http://facebook.com/#{user.facebook_url}" %>
		  <% end %>	
		  <% unless user.twitter_url.blank? %>
		  	<%= link_to image_tag('twitter_icon.png', :class => 'social_icons'), "http://twitter.com/#{user.twitter_url}" %>
		  <% end %>	
		</li>
		  
	  <li>
	  	<a href="<%= user_path(user) %>">View Full Profile</a>
	  </li>
	</ul>  
</div>

app/views/users/cohort_reselect.html.erb
<%= form_for @user do |f| %>
	<%= f.label "Current Cohort:" %>
	<%= f.collection_select :cohort_id, @cohorts, :id, :name %>

	<p><%= f.submit "Select new cohort" %></p>
<% end %>

app/views/users/edit.html.erb
<div class="welcome">Welcome, <%= @user.first_name %>!</div>

<%= form_for @user, :html => {:class => "form-horizontal user-form"} do |f| %>
  <div id='update_group'>
    <div class="control-group">
      <%= f.label :First_Name, :class => "control-label" %>
      <%= f.text_field :first_name, :class => "controls"  %> 
    </div>
    <div class="control-group">
      <%= f.label :Last_name, :class => "control-label"  %>
      <%= f.text_field :last_name, :class => "controls" %>
    </div>
    <div class="control-group">
      <%= f.label :Email_Address, :class => "control-label" %>
      <%= f.email_field :email, :class => "controls" %>
    </div>
    <div class="control-group">
      <%= f.label :Phone, :class => "control-label" %>
      <%= f.text_field :phone_number, :class => "controls" %>
    </div>
    <div class="control-group">
      <%= f.label :Company, :class => "control-label" %>
      <%= f.text_field :company, :class => "controls" %> 
    </div>
    <div class="control-group">
      <%= f.label :Location, :class => "control-label" %>
      <%= f.text_field :location, :class => "controls" %>
    </div>
    <div class="control-group">
      <%= f.label :Advice_tweet, :class => "control-label" %>
      <%= f.text_field :advice, :class => "controls" %>
    </div>
    <div class="control-group">
      <%= f.label :Best_places_to_eat_near_DBC, :class => "control-label" %>
      <%= f.text_field :restaurant, :class => "controls" %>
    </div>
    <div class="control-group">
      <%= f.label "Website URL", :class => "control-label" %>
      <%= f.text_field :website_url, :class => "controls" %>
    </div>
    <div class="control-group">
      <%= f.label "Blog URL", :class => "control-label" %>
      <%= f.text_field :blog_url, :class => "controls" %>
    </div>
    <div class="control-group">
      <%= f.label "Linked In (add full URL)", :class => "control-label" %>
      <%= f.text_field :linkedin_url, :class => "controls" %>
    </div>
    <div class="control-group">
      <%= f.label "Facebook Handle", :class => "control-label" %>
      <%= f.text_field :facebook_url, :class => "controls", :placeholder => "facebook.com/username" %>
      <% if @show_facebook %><div class="button facebook"><%= link_to "Connect", "/auth/facebook" %></div><% end %>
    </div>
    <div class="control-group">
      <%= f.label "Twitter Handle", :class => "control-label" %>
      <%= f.text_field :twitter_url, :class => "controls", :placeholder => "twitter.com/username" %>
      <% if @show_twitter %><div class="button twitter"><%= link_to "Connect", "/auth/twitter" %></div><% end %>
    </div>
  </div>

  <% unless @user.photo_url %>
    <%= render "photos", f: f %>
  <% else %>
    
      <div class="control-group">
        
        
        <div class="change">
          <div class="profile_img">
          <%= image_tag @user.photo_url %>
          <span><%= @user.name %></span>
        </div>

          <%= link_to "Change Photo", user_photo_path(@user) %>
          <%= link_to "Change Cohort", {:action=>"cohort_reselect", :controller=>"users"} %>
        </div>
      </div>
      
  
    
  <% end %>

  <div class="control-group">
    <div class="control-label"></div>
    <%= f.submit "Update", :class => "controls" %>
  </div>

<% end %>

app/views/users/index.html.erb
<% if @cohort %>
  <h2><%= @cohort.name %></h2>
<% end %>

<%if current_user %>
  <ul class="table users">
    <% @users.each do |user| %>
      <li>
        <% if user.first_name && user.last_name %>
          <%= link_to "#{user.first_name} #{user.last_name}", user_path(user) %>
        <% elsif user.email %>
          <%= link_to user.email, user_path(user) %>
        <% else %>
          <%= link_to user.id, user_path(user) %>
        <% end %>
      </li>
    <% end %>
  </ul>
<% end %>
</div>

app/views/users/photo.html.erb
<%= form_for @user, :html => {:class => "form-horizontal"} do |f| %>
  <%= render "photos", f: f %>
  <%= f.submit "Update", :class => "controls" %>
<% end %>

app/views/users/show.html.erb
<% if @user == current_user %>
  <div class="welcome">Welcome, <%= @user.first_name %>!</div>
<% end %>

<div class="profile_img">
  <%= image_tag @user.photo %>
  <span><%= @user.name %></span>
</div>
  
<div>
<ul id='user_info'>
  <li><div class="profile_label">Cohort:</div> <%= @user.cohort.name %></li>
  <li><div class="profile_label">Email:</div> <%= mail_to "#{@user.email}" %></li>
  <% if @user.birthday %><li><div class="profile_label">Birthday: <%= @user.birthday %></div></li><% end %>
  <li><div class="profile_label">Phone #:</div> <%= phone_number_link(@user.phone_number) %></li>
  <li><div class="profile_label">Current company:</div> <%= @user.company %></li>
  <li><div class="profile_label">Current city:</div> <%= @user.location %></li>
  <li><div class="profile_label">Website:</div> <%= link_to @user.website_url, "http://#{@user.website_url}" %></li>
  <li><div class="profile_label">Blog:</div> <%= link_to @user.blog_url, "http://#{@user.blog_url}" %></li>
  <li><div class="profile_label">Advice Tweet:</div> &ldquo;<%= @user.advice %>&rdquo;</li>
  <li><div class="profile_label">Favorite Restaurant:</div> <%= @user.restaurant %></li>
  <li><div class="profile_label">Github Profile:</div> <%= link_to @user.nickname, "http://github.com/#{@user.nickname}" %></li>
  <li><div class="profile_label">LinkedIn Profile: <%= link_to @user.linkedin_url, @user.linkedin_url %></div></li>
  <li><div class="profile_label">Facebook Profile:</div> <%= link_to @user.facebook_url, "http://facebook.com/#{@user.facebook_url}" %></li>
  <li><div class="profile_label">Twitter Profile:</div> <%= link_to "@#{@user.twitter_url}", "http://twitter.com/#{@user.twitter_url}" %></li>
  
  <% if current_user.admin? %>
    <p><%= link_to "Delete", user_path(@user), method: :delete %></p>
  <% end %>

</div>

app/views/users/update.html.erb
this file might be needed for something to work 