config/routes.rb
Phaseboot::Application.routes.draw do

  mount Forem::Engine, :at => '/forums'

  root to: "pages#index"
  get "/admin" => "pages#admin", :as => :admin
  post '/pages/search'
  get '/auth/:provider/callback', to: 'sessions#create'
  post '/search' => 'users#query'
  get '/users/cohort_reselect'

  match "/signout" => "sessions#destroy", :as => :signout

  resources :users do
    get "/photo" => "users#photo"
  end

  resources :sessions, only: [:new, :create, :destroy]
  resources :access, only: [:show]
  
  resources :cohorts do
    resources :users, only: [:index]
  end

  

end

app/views/forem/forums/_forum.html.erb
<% if can?(:read, forum) %>
  <tr class="forum <%= cycle("odd", "even") %>">
    <td>
      <%= link_to forem_emojify(forum.title), forem.forum_path(forum), :class => "title" %>
      <div class='description'><%= forem_format(forum.description) %></div>
    
    </td>
    <td class="topics-count"><%= topics_count(forum) %></td>
    <td class="posts-count"><%= posts_count(forum) %></td>
    <td class="views-count"><%= forum.views_count %></td>
  </tr>
<% end %>

app/views/forem/forums/_head.html.erb
<div id='forum'>
  <h2><%= link_to t('forem.forum.forums'), forem.root_path %> &raquo; <%= link_to forem_emojify(forum.category), [forem, forum.category] %> &raquo; <%= link_to forem_emojify(forum.title), [forem, forum] %></h2>
  <span id='description'><%= forem_format(forum.description) %></span>
  <menu id='forum_topic_links'>
    <% unless @topic.try(:new_record?) %>
      <% if can? :create_topic, @forum %>
        <%= link_to t('forem.topic.links.new'), forem.new_forum_topic_path(forum) %>
      <% end %>
    <% end %>
    <% if @topic %>
      <%= link_to t('forem.topic.links.back_to_topics'), forem.forum_path(forum) %>
    <% end %>
    <% if can? :moderate, @forum %>
      <%= link_to t('forem.forum.moderator_tools'), forem.forum_moderator_tools_path(forum) %>
    <% end %>
  </menu>

  <% if @search %>
    <%= form_tag search_forum_path(@forum), :method=>:get do %>
    <%= text_field_tag :q, @search %>
    <%= submit_tag "Search" %>
   <% end %> 
<% end %>

app/views/forem/forums/_listing.html.erb
<table id='forums' class='forums subdued' cellspacing='0'>
  <thead>
  <tr>
    <th class="desc-and-last-post"><%= t('forum', :scope => 'forem.general') %></th>
    <th class="topics-count"><%= t('topics', :scope => 'forem.general') %></th>
    <th class="posts-count"><%= t('posts', :scope => 'forem.general') %></th>
    <th class="views-count"><%= t('forem.forums.index.views') %></th>
  </tr>
  </thead>
  <tbody>
    <%= render category.forums %>
  </tbody>
</table>

app/views/forem/forums/index.html.erb
<div id='forums_container'>
  <h1 id='forums_title'><%= t('.title') %></h1>
  <% if forem_admin? %>
    <%= link_to t("area", :scope => "forem.admin"), forem.admin_root_path %>
  <% end %>

  <%= render @categories %>
</div>

<br>
<footer id='admin_link'>
  
</footer>

app/views/forem/forums/show.html.erb
<%= render :partial => 'forem/forums/head', :locals => { :forum => @forum } %>

<%= forem_pages_widget(@topics) %>
<% #search_forum_path @forum %>



<table class='topics subdued' cellspacing='0'>
  <thead>
    <tr>
      <th class="icon"></th>
      <th class="byline"><%= t('forem.topic.headings.topic') -%></th>
      <th class="latest-post"><%= t('forem.topic.headings.latest') -%></th>
      <th class="posts-count"><%= t('forem.topic.headings.posts') -%></th>
      <th class="views-count"><%= t('forem.topic.headings.views') -%></th>
    </tr>
  </thead>
  <tbody>
    <% if @topics.empty? %>
      <tr><td colspan='5' align='center'><%= t('forem.topic.none') %></td></tr>
    <% end %>
    <%= render @topics %>
  </tbody>
</table>

<%= forem_pages_widget(@topics) %>